services:
  - type: web
    name: portfolio-optimizer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run portfolio_app.py --server.port=10000
